version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: sharedspace/app
    volumes:
     - .:/var/www/html
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: sharedspace/node
    volumes:
     - .:/var/www/html
  mysql:
    image: mysql:5.7
    volumes:
     - mysqldata:/var/lib/mysql
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
