/*

Tailwind - The Utility-First CSS Framework

A project by Adam Wathan (@adamwathan), Jonathan Reinink (@reinink),
David Hemphill (@davidhemphill) and Steve Schoger (@steveschoger).

Welcome to the Tailwind config file. This is where you can customize
Tailwind specifically for your project. Don't be intimidated by the
length of this file. It's really just a big JavaScript object and
we've done our very best to explain each section.

View the full documentation at https://tailwindcss.com.


|-------------------------------------------------------------------------------
| The default config
|-------------------------------------------------------------------------------
|
| This variable contains the default Tailwind config. You don't have
| to use it, but it can sometimes be helpful to have available. For
| example, you may choose to merge your custom configuration
| values with some of the Tailwind defaults.
|
*/
module.exports = {
    prefix: '',
    important: false,
    separator: ':',
    theme: {
        extend: {
            spacing: {
                'full': '100%',
                '1/2': '50%',
                '1/3': '33.333333%',
                '2/3': '66.666667%',
                '1/4': '25%',
                '2/4': '50%',
                '3/4': '75%',
                '1/5': '20%',
                '2/5': '40%',
                '3/5': '60%',
                '4/5': '80%',
                '1/6': '16.666667%',
                '2/6': '33.333333%',
                '3/6': '50%',
                '4/6': '66.666667%',
                '5/6': '83.333333%',
                '1/12': '8.333333%',
                '2/12': '16.666667%',
                '3/12': '25%',
                '4/12': '33.333333%',
                '5/12': '41.666667%',
                '6/12': '50%',
                '7/12': '58.333333%',
                '8/12': '66.666667%',
                '9/12': '75%',
                '10/12': '83.333333%',
                '11/12': '91.666667%',
                '1px': '1px',
                '2px': '2px'
            },
            screens: {
                sm: '640px',
                md: '768px',
                lg: '1024px',
                xl: '1280px',
            },
            colors: {
                transparent: 'transparent',

                black: '#000',
                white: '#fff',

                gray: {
                    100: '#f7fafc',
                    200: '#edf2f7',
                    300: '#d7d7d7',
                    400: '#cbd5e0',
                    500: '#a0aec0',
                    600: '#718096',
                    700: '#4a4a4a',
                    800: '#2d3748',
                    900: '#1a202c',
                },
                red: {
                    100: '#fff5f5',
                    200: '#fed7d7',
                    300: '#feb2b2',
                    400: '#fac4B1',
                    500: '#f56565',
                    600: '#e53e3e',
                    700: '#c53030',
                    800: '#9b2c2c',
                    900: '#742a2a',
                },
                orange: {
                    100: '#fffaf0',
                    200: '#feebc8',
                    300: '#fbd38d',
                    400: '#f6ad55',
                    500: '#ed8936',
                    600: '#dd6b20',
                    700: '#c05621',
                    800: '#9c4221',
                    900: '#7b341e',
                },
                yellow: {
                    100: '#fffff0',
                    200: '#fefcbf',
                    300: '#faf089',
                    400: '#fce386',
                    500: '#ecc94b',
                    600: '#d69e2e',
                    700: '#b7791f',
                    800: '#975a16',
                    900: '#744210',
                },
                green: {
                    100: '#f0fff4',
                    200: '#c2e09a',
                    300: '#9ae6b4',
                    400: '#68d391',
                    500: '#48bb78',
                    600: '#38a169',
                    700: '#2f855a',
                    800: '#276749',
                    900: '#22543d',
                },
                teal: {
                    100: '#e6fffa',
                    200: '#b2f5ea',
                    300: '#81e6d9',
                    400: '#4fd1c5',
                    500: '#38b2ac',
                    600: '#319795',
                    700: '#2c7a7b',
                    800: '#285e61',
                    900: '#234e52',
                },
                blue: {
                    100: '#ebf8ff',
                    200: '#bee3f8',
                    300: '#90cdf4',
                    400: '#63b3ed',
                    500: '#4299e1',
                    600: '#3182ce',
                    700: '#2b6cb0',
                    800: '#2c5282',
                    900: '#2a4365',
                },
                indigo: {
                    100: '#ebf4ff',
                    200: '#c3dafe',
                    300: '#a3bffa',
                    400: '#7f9cf5',
                    500: '#667eea',
                    600: '#5a67d8',
                    700: '#4c51bf',
                    800: '#434190',
                    900: '#3c366b',
                },
                purple: {
                    100: '#faf5ff',
                    200: '#e9d8fd',
                    300: '#d6bcfa',
                    400: '#b794f4',
                    500: '#9f7aea',
                    600: '#805ad5',
                    700: '#6b46c1',
                    800: '#553c9a',
                    900: '#44337a',
                },
                pink: {
                    100: '#fff5f7',
                    200: '#fed7e2',
                    300: '#fbb6ce',
                    400: '#f687b3',
                    500: '#ed64a6',
                    600: '#d53f8c',
                    700: '#b83280',
                    800: '#97266d',
                    900: '#702459',
                },
                smoke: {
                    100: 'rgba(0, 0, 0, 0.1)',
                    200: 'rgba(0, 0, 0, 0.2)',
                    300: 'rgba(0, 0, 0, 0.3)',
                    400: 'rgba(0, 0, 0, 0.4)',
                    500: 'rgba(0, 0, 0, 0.5)',
                    600: 'rgba(0, 0, 0, 0.6)',
                    700: 'rgba(0, 0, 0, 0.7)',
                    800: 'rgba(0, 0, 0, 0.8)',
                    900: 'rgba(0, 0, 0, 0.9)'
                }
            },
            backgroundColor: theme => theme('colors'),
            backgroundPosition: {
                bottom: 'bottom',
                center: 'center',
                left: 'left',
                'left-bottom': 'left bottom',
                'left-top': 'left top',
                right: 'right',
                'right-bottom': 'right bottom',
                'right-top': 'right top',
                top: 'top',
            },
            backgroundSize: {
                auto: 'auto',
                cover: 'cover',
                contain: 'contain',
            },
            borderColor: theme => ({
                ...theme('colors'),
                default: theme('colors.gray.300', 'currentColor'),
            }),
            borderRadius: {
                none: '0',
                sm: '0.125rem',
                default: '0.25rem',
                lg: '0.5rem',
                full: '9999px',
            },
            borderWidth: {
                default: '1px',
                '0': '0',
                '2': '2px',
                '4': '4px',
                '8': '8px',
            },
            boxShadow: {
                default: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
                md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
                lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
                xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
                '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
                inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
                outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
                none: 'none',
            },
            container: {},
            cursor: {
                auto: 'auto',
                default: 'default',
                pointer: 'pointer',
                wait: 'wait',
                text: 'text',
                move: 'move',
                'not-allowed': 'not-allowed',
            },
            fill: {
                current: 'currentColor',
            },
            flex: {
                '1': '1 1 0%',
                auto: '1 1 auto',
                initial: '0 1 auto',
                none: 'none',
            },
            flexGrow: {
                '0': '0',
                default: '1',
            },
            flexShrink: {
                '0': '0',
                default: '1',
            },
            fontFamily: {
                sans: [
                    'Lato',
                    '-apple-system',
                    'BlinkMacSystemFont',
                    '"Segoe UI"',
                    'Roboto',
                    '"Helvetica Neue"',
                    'Arial',
                    '"Noto Sans"',
                    'sans-serif',
                    '"Apple Color Emoji"',
                    '"Segoe UI Emoji"',
                    '"Segoe UI Symbol"',
                    '"Noto Color Emoji"',
                ],
                serif: [
                    'Georgia',
                    'Cambria',
                    '"Times New Roman"',
                    'Times',
                    'serif',
                ],
                mono: [
                    'Menlo',
                    'Monaco',
                    'Consolas',
                    '"Liberation Mono"',
                    '"Courier New"',
                    'monospace',
                ],
            },
            fontSize: {
                xs: '0.75rem',
                sm: '0.875rem',
                base: '1rem',
                lg: '1.125rem',
                xl: '1.25rem',
                '2xl': '1.5rem',
                '3xl': '1.875rem',
                '4xl': '2.25rem',
                '5xl': '3rem',
                '6xl': '4rem',
            },
            fontWeight: {
                hairline: '100',
                thin: '200',
                light: '300',
                normal: '400',
                medium: '500',
                semibold: '600',
                bold: '700',
                extrabold: '800',
                black: '900',
            },
            height: theme => ({
                auto: 'auto',
                ...theme('spacing'),
                full: '100%',
                screen: '100vh',
            }),
            inset: {
                '0': '0',
                auto: 'auto',
            },
            letterSpacing: {
                tighter: '-0.05em',
                tight: '-0.025em',
                normal: '0',
                wide: '0.025em',
                wider: '0.05em',
                widest: '0.1em',
            },
            lineHeight: {
                none: '1',
                tight: '1.25',
                snug: '1.375',
                normal: '1.5',
                relaxed: '1.625',
                loose: '2',
            },
            listStyleType: {
                none: 'none',
                disc: 'disc',
                decimal: 'decimal',
            },
            margin: (theme, { negative }) => ({
                auto: 'auto',
                ...theme('spacing'),
                ...negative(theme('spacing')),
            }),
            maxHeight: {
                full: '100%',
                screen: '100vh',
            },
            maxWidth: {
                xs: '20rem',
                sm: '24rem',
                md: '28rem',
                lg: '32rem',
                xl: '36rem',
                '2xl': '42rem',
                '3xl': '48rem',
                '4xl': '56rem',
                '5xl': '64rem',
                '6xl': '72rem',
                full: '100%',
            },
            minHeight: {
                '0': '0',
                full: '100%',
                screen: '100vh',
            },
            minWidth: {
                '0': '0',
                full: '100%',
            },
            objectPosition: {
                bottom: 'bottom',
                center: 'center',
                left: 'left',
                'left-bottom': 'left bottom',
                'left-top': 'left top',
                right: 'right',
                'right-bottom': 'right bottom',
                'right-top': 'right top',
                top: 'top',
            },
            opacity: {
                '0': '0',
                '25': '0.25',
                '50': '0.5',
                '75': '0.75',
                '100': '1',
            },
            order: {
                first: '-9999',
                last: '9999',
                none: '0',
                '1': '1',
                '2': '2',
                '3': '3',
                '4': '4',
                '5': '5',
                '6': '6',
                '7': '7',
                '8': '8',
                '9': '9',
                '10': '10',
                '11': '11',
                '12': '12',
            },
            padding: theme => theme('spacing'),
            placeholderColor: theme => theme('colors'),
            stroke: {
                current: 'currentColor',
            },
            textColor: theme => theme('colors'),
            width: theme => ({
                auto: 'auto',
                ...theme('spacing'),
                '1/2': '50%',
                '1/3': '33.333333%',
                '2/3': '66.666667%',
                '1/4': '25%',
                '2/4': '50%',
                '3/4': '75%',
                '1/5': '20%',
                '2/5': '40%',
                '3/5': '60%',
                '4/5': '80%',
                '1/6': '16.666667%',
                '2/6': '33.333333%',
                '3/6': '50%',
                '4/6': '66.666667%',
                '5/6': '83.333333%',
                '1/12': '8.333333%',
                '2/12': '16.666667%',
                '3/12': '25%',
                '4/12': '33.333333%',
                '5/12': '41.666667%',
                '6/12': '50%',
                '7/12': '58.333333%',
                '8/12': '66.666667%',
                '9/12': '75%',
                '10/12': '83.333333%',
                '11/12': '91.666667%',
                full: '100%',
                screen: '100vw',
            }),
            transitionProperty: { // defaults to these values
                'none': 'none',
                'all': 'all',
                'color': 'color',
                'bg': 'background-color',
                'border': 'border-color',
                'colors': ['color', 'background-color', 'border-color'],
                'opacity': 'opacity',
                'transform': 'transform',
            },
            transitionDuration: { // defaults to these values
                'default': '250ms',
                '0': '0ms',
                '100': '100ms',
                '250': '250ms',
                '500': '500ms',
                '750': '750ms',
                '1000': '1000ms',
            },
            transitionTimingFunction: { // defaults to these values
                'default': 'ease',
                'linear': 'linear',
                'ease': 'ease',
                'ease-in': 'ease-in',
                'ease-out': 'ease-out',
                'ease-in-out': 'ease-in-out',
            },
            transitionDelay: { // defaults to these values
                'default': '0ms',
                '0': '0ms',
                '100': '100ms',
                '250': '250ms',
                '500': '500ms',
                '750': '750ms',
                '1000': '1000ms',
            },
            willChange: { // defaults to these values
                'auto': 'auto',
                'scroll': 'scroll-position',
                'contents': 'contents',
                'opacity': 'opacity',
                'transform': 'transform',
            },
            zIndex: {
                auto: 'auto',
                '0': '0',
                '10': '10',
                '20': '20',
                '30': '30',
                '40': '40',
                '50': '50',
            },
        },
        variants: {
            accessibility: ['responsive', 'focus'],
            alignContent: ['responsive'],
            alignItems: ['responsive'],
            alignSelf: ['responsive'],
            appearance: ['responsive'],
            backgroundAttachment: ['responsive'],
            backgroundColor: ['responsive', 'hover', 'focus'],
            backgroundPosition: ['responsive'],
            backgroundRepeat: ['responsive'],
            backgroundSize: ['responsive'],
            borderCollapse: ['responsive'],
            borderColor: ['responsive', 'hover', 'focus'],
            borderRadius: ['responsive'],
            borderStyle: ['responsive'],
            borderWidth: ['responsive'],
            boxShadow: ['responsive', 'hover', 'focus'],
            cursor: ['responsive'],
            display: ['responsive'],
            fill: ['responsive'],
            flex: ['responsive'],
            flexDirection: ['responsive'],
            flexGrow: ['responsive'],
            flexShrink: ['responsive'],
            flexWrap: ['responsive'],
            float: ['responsive'],
            fontFamily: ['responsive'],
            fontSize: ['responsive'],
            fontSmoothing: ['responsive'],
            fontStyle: ['responsive'],
            fontWeight: ['responsive', 'hover', 'focus'],
            height: ['responsive'],
            inset: ['responsive'],
            justifyContent: ['responsive'],
            letterSpacing: ['responsive'],
            lineHeight: ['responsive'],
            listStylePosition: ['responsive'],
            listStyleType: ['responsive'],
            margin: ['responsive'],
            maxHeight: ['responsive'],
            maxWidth: ['responsive'],
            minHeight: ['responsive'],
            minWidth: ['responsive'],
            objectFit: ['responsive'],
            objectPosition: ['responsive'],
            opacity: ['responsive', 'hover', 'focus'],
            order: ['responsive'],
            outline: ['responsive', 'focus'],
            overflow: ['responsive'],
            padding: ['responsive'],
            placeholderColor: ['responsive', 'focus'],
            pointerEvents: ['responsive'],
            position: ['responsive'],
            resize: ['responsive'],
            stroke: ['responsive'],
            tableLayout: ['responsive'],
            textAlign: ['responsive'],
            textColor: ['responsive', 'hover', 'focus'],
            textDecoration: ['responsive', 'hover', 'focus'],
            textTransform: ['responsive'],
            transitionProperty: ['responsive'],
            transitionDuration: ['responsive'],
            transitionTimingFunction: ['responsive'],
            transitionDelay: ['responsive'],
            userSelect: ['responsive'],
            verticalAlign: ['responsive'],
            visibility: ['responsive'],
            whitespace: ['responsive'],
            width: ['responsive'],
            willChange: ['responsive'],
            wordBreak: ['responsive'],
            zIndex: ['responsive'],
        }
    },
    corePlugins: {},
    plugins: [
        require('tailwindcss-transitions')(),
    ],
}


/*
|-------------------------------------------------------------------------------
| Colors                                    https://tailwindcss.com/docs/colors
|-------------------------------------------------------------------------------
|
| Here you can specify the colors used in your project. To get you started,
| we've provided a generous palette of great looking colors that are perfect
| for prototyping, but don't hesitate to change them for your project. You
| own these colors, nothing will break if you change everything about them.
|
| We've used literal color names ("red", "blue", etc.) for the default
| palette, but if you'd rather use functional names like "primary" and
| "secondary", or even a numeric scale like "100" and "200", go for it.
|
*/

// let colors2 = {
//   'transparent': 'transparent',
//
//   'black': '#22292f',
//   'grey-darkest': '#4a4a4a',
//   'grey-darker': '#606f7b',
//   'grey-dark': '#8795a1',
//   'grey': '#b8c2cc',
//   'grey-light': '#c1c1c1',
//   'grey-lighter': '#f1f5f8',
//   'grey-lightest': '#f8fafc',
//   'white': '#ffffff',
//
//   'red-darkest': '#3b0d0c',
//   'red-darker': '#621b18',
//   'red-dark': '#cc1f1a',
//   'red': '#e3342f',
//   'red-light': '#ef5753',
//   'red-lighter': '#f9acaa',
//   'red-lightest': '#fcebea',
//
//   'orange-darkest': '#462a16',
//   'orange-darker': '#613b1f',
//   'orange-dark': '#de751f',
//   'orange': '#f6993f',
//   'orange-light': '#faad63',
//   'orange-lighter': '#fcd9b6',
//   'orange-lightest': '#fff5eb',
//
//   'yellow-darkest': '#453411',
//   'yellow-darker': '#684f1d',
//   'yellow-dark': '#EBDA41',
//   'yellow': '#ffed4a',
//   'yellow-light': '#fff382',
//   'yellow-lighter': '#fff9c2',
//   'yellow-lightest': '#fcfbeb',
//
//   'green-darkest': '#0f2f21',
//   'green-darker': '#1a4731',
//   'green-dark': '#1f9d55',
//   'green': '#38c172',
//   'green-light': '#51d88a',
//   'green-lighter': '#a2f5bf',
//   'green-lightest': '#e3fcec',
//
//   'teal-darkest': '#0d3331',
//   'teal-darker': '#20504f',
//   'teal-dark': '#38a89d',
//   'teal': '#4dc0b5',
//   'teal-light': '#6ec7c0',
//   'teal-lighter': '#aae0d1',
//   'teal-lightest': '#e8fffe',
//
//   'blue-darkest': '#12283a',
//   'blue-darker': '#1c3d5a',
//   'blue-dark': '#2779bd',
//   'blue': '#4a90e2',
//   'blue-light': '#6cb2eb',
//   'blue-lighter': '#bcdefa',
//   'blue-lightest': '#eff8ff',
//
//   'indigo-darkest': '#191e38',
//   'indigo-darker': '#2f365f',
//   'indigo-dark': '#5661b3',
//   'indigo': '#6574cd',
//   'indigo-light': '#7886d7',
//   'indigo-lighter': '#b2b7ff',
//   'indigo-lightest': '#e6e8ff',
//
//   'purple-darkest': '#21183c',
//   'purple-darker': '#382b5f',
//   'purple-dark': '#794acf',
//   'purple': '#9561e2',
//   'purple-light': '#a779e9',
//   'purple-lighter': '#d6bbfc',
//   'purple-lightest': '#f3ebff',
//
//   'pink-darkest': '#451225',
//   'pink-darker': '#6f213f',
//   'pink-dark': '#eb5286',
//   'pink': '#f66d9b',
//   'pink-light': '#fa7ea8',
//   'pink-lighter': '#ffbbca',
//   'pink-lightest': '#ffebef',
//
//   'smoke-darkest': 'rgba(0, 0, 0, 0.9)',
//   'smoke-darker': 'rgba(0, 0, 0, 0.75)',
//   'smoke-dark': 'rgba(0, 0, 0, 0.6)',
//   'smoke': 'rgba(0, 0, 0, 0.5)',
//   'smoke-light': 'rgba(0, 0, 0, 0.4)',
//   'smoke-lighter': 'rgba(0, 0, 0, 0.25)',
//   'smoke-lightest': 'rgba(0, 0, 0, 0.1)',
// }
